var BGM_list = {
    1: "青空Magic_Day-日.m4a",
    2: "正午天空的月亮.m4a",
    3: "青春档案.m4a",
    4: "エブリディいっしょ♪.m4a",
    5: "晄轮大会的小曲.ogg",
    6: "可愛くなるレッスン.m4a",
    7: "登录的小曲.ogg",
    8: "希望の朝へ.m4a",
    9: "Unwelcome_School.ogg",
    10: "Connected_Sky.m4a",
    11: "優しさの記憶.m4a",
    12: "澄んだ青空、萌ゆる心.m4a",
    13: "青色コントラスト.m4a",
    14: "青空Magic_Day-中.m4a",
    15: "After_the_Beep.m4a",
    16: "Shooting_Stars.m4a",
    17: "Future_Bossa.m4a",
    18: "Midsummer_cat.m4a",
    19: "Welcome_School.m4a",
    20: "恋愛サーキュレーション.wav",
    21: "恋愛サーキュレーション-AI-天童爱丽丝.mp3"
};
